name: Publish binaries

on: push

jobs:
  package:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pkg
        run: npm install -g pkg
      - name: Package
        run: npm run package
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: bin
          path: bin/

  test:
    needs: ["package"]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download
        uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
      - name: Test Linux binary
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: chmod +x ./bin/cricket-live-scores-linux && ./bin/cricket-live-scores-linux
      - name: Test Windows binary
        if: ${{ matrix.os == 'windows-latest' }}
        run: chmod +x ./bin/cricket-live-scores-win.exe && ./bin/cricket-live-scores-win.exe

  release:
    permissions: write-all
    needs: ["test"]
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: bin
          path: bin/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: bin/*
